version: "3"
services:
  apache:
    build:
      context: "./docker/httpd"
    container_name: '${COMPOSE_PROJECT_NAME}-apache'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes:
      - ${DOCUMENT_ROOT}:/var/www:cached
    restart: unless-stopped
 